albaranes:
  item: [item]
  fecha_servicio: [fecha_servicio, fecha_de_servicio]
  concepto_denominacion_evento_asociado: [concepto_denominacion_evento_asociado, concepto_evento, concepto]
  descripcion: [descripcion, codigo_servicio, descripcion_servicio]
  solicitante_mahou: [solicitante_mahou]
  dpto_mahou: [dpto_mahou, departamento_mahou]
  pales_in: [pales_in, palets_in]
  cajas_in: [cajas_in]
  m3_in: [m3_in]
  pales_out: [pales_out, palets_out]
  embalaje_con_manipulacion: [embalaje_con_manipulacion]
  m3_out: [m3_out]
  noches_desplazam_x_operario: [noches_desplazam_x_operario]
  cp: [cp]
  urgencia: [urgencia]
  festivo: [festivo]
  provincia_destino: [provincia_destino]
  tiempo_reloj_transporte_horas: [tiempo_reloj_transporte_horas]
  tiempo_reloj_carga_y_descarga_horas: [tiempo_reloj_carga_y_descarga_horas]
  no_operarios_sin_contar_chofer: [no_operarios_sin_contar_chofer]
  peso_kg_raw: [peso_kg, peso]
  volumen: [volumen]
  cajas_out: [cajas_out]
movimientos:
  tipo_movimiento: [tipo_movimiento]
  fecha_inicio: [fecha_inicio]
  fecha_finalizacion: [fecha_finalizacion]
  articulo: [articulo]
  denominacion_articulo: [denominacion_articulo]
  cantidad: [cantidad]
  operario: [operario]
  denominacion_operario: [denominacion_operario]
  ubicacion: [ubicacion]
  pedido: [pedido]
  pedido_externo: [pedido_externo]
  cliente: [cliente]
  cliente_externo: [cliente_externo]
solicitudes:
  id: [id]
  solicitud: [solicitud]
  inicio_evento: [inicio_evento]
  creacion_solicitud: [creacion_solicitud]
  borrado_solicitud: [borrado_solicitud]
  pedido: [pedido]
  articulo: [articulo]
  propietario: [propietario]
  departamento: [departamento]
  estado_linea: [estado_linea]
  cant_solicitada: [cant_solicitada]
  cant_confirmada: [cant_confirmada]
  cant_almacenada: [cant_almacenada]
  modificacion_linea: [modificacion_linea]
  fin_evento: [fin_evento]
  reservation_start_date: [reservation_start_date]
  reservation_finish_date: [reservation_finish_date]
  borrado_linea: [borrado_linea]
  alta_baja: [alta_baja]
  comentarios: [comentarios]
  estado: [estado]
  creacion_pedido: [creacion_pedido]
  ultima_modificacion: [ultima_modificacion]
  provincia: [provincia]
  codigo_generico: [codigo_generico]
maestro:
  codigo: [codigo]
  nombre: [nombre]
  categoria: [categoria]
  creacion: [creacion]
  kilos: [kilos]
  m2: [m2]
  m3: [m3]
  largo: [largo]
  ancho: [ancho]
  alto: [alto]
